# Base image
FROM ubuntu:latest

# Install dnsmasq
RUN apt-get update && apt-get install -y dnsmasq && rm -rf /var/lib/apt/lists/*

# Expose DNS port
EXPOSE 53/udp

# Start dnsmasq
CMD ["dnsmasq", "-k"]
