version: '3'

services:
  dnsmasq:
    build: .
    container_name: dnsmasq
    ports:
      - "53:53/udp"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    restart: unless-stopped
